#ifndef FLOATING_POINT_FUNCTIONS_INCLUDE_FUNCTIONS_HPP
#define FLOATING_POINT_FUNCTIONS_INCLUDE_FUNCTIONS_HPP

namespace functions {
double exp(double exponent);
}

#endif  // FLOATING_POINT_FUNCTIONS_INCLUDE_FUNCTIONS_HPP
